version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      typescript-ecosystem:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "ts-node"
          - "@types/*"
      drizzle-ecosystem:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
          
    ignore:
      - dependency-name: "discord.js"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
